on: [push, workflow_dispatch]
name: 'Trigger new update'
jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "Notify about update"
    strategy:
      matrix:
        repo: ['https://github.com/HarryKayNeezy/test-repo-01', 'https://github.com/HarryKayNeezy/test-repo-02']
    steps:
    - uses: HarryKayNeezy/test-repo-01@master
      env:
        PAYLOAD_REBUILD: "false"
        PAYLOAD_BRANCH: ${{github.ref}}
      with:
        repository: HarryKayNeezy/${{ matrix.repo }}
        event: update
        github_pat: ${{ secrets.ACTIONS_KEY }}
