name: Trigger Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.ACTIONS_KEY}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/HarryKayNeezy/test-repo-02/github/workflows/deploy.yml/dispatches \
          -d '{"ref": "master"}'
