on: [push, workflow_dispatch]
name: 'Trigger new update'
jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "Notify about update"
    strategy:
      matrix:
        repo: ['test-repo-01', 'test-repo-2']
    steps:
    - uses: passeidireto/trigger-external-workflow-action@main
      env:
        PAYLOAD_REBUILD: "false"
        PAYLOAD_BRANCH: ${{github.ref}}
      with:
        repository: HarryKayNeezy/${{ matrix.repo }}
        event: update
        github_pat: ${{ secrets.ACTIONS_KEY }}
